import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@rainbow-me/rainbowkit/styles.css'
import { NextUiProvider } from '@/providers/nextUiProvider'
import { RainbowProvider } from '@/providers/rainbowProvider'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUiProvider>
          <RainbowProvider>
            <Navbar />
            {children}
          </RainbowProvider>
        </NextUiProvider>
      </body>
    </html>
  )
}
